import json
import os
from datetime import datetime
from pathlib import Path
from jinja2 import Environment, FileSystemLoader


# ── Report Template ───────────────────────────────────────────────────────────
REPORT_TEMPLATE = """# Threat Model Report: {{ system_name }}

**Generated:** {{ generated_at }}
**Tool:** ThreatLens AI — STRIDE + Agentic AI + CVSS 3.1
**Methodology:** STRIDE | Single-Agent (SA) | Multi-Agent (MA) | CVSS 3.1

---

## Executive Summary

**{{ system_name }}** threat model identified **{{ total_threats }} threats**
across **{{ component_count }} components** and **{{ flow_count }} data flows**.

| Severity | Count |
|----------|-------|
| 🔴 Critical | {{ severity_summary.Critical }} |
| 🟠 High | {{ severity_summary.High }} |
| 🟡 Medium | {{ severity_summary.Medium }} |
| 🟢 Low | {{ severity_summary.Low }} |
| ⚪ Informational | {{ severity_summary.Informational }} |

**Threat Breakdown by Framework:**

| Framework | Count |
|-----------|-------|
| STRIDE (Traditional App) | {{ stride_count }} |
| Single-Agent AI (SA) | {{ single_agent_count }} |
| Multi-Agent AI (MA) | {{ multi_agent_count }} |

**Top 5 Priority Threats:**
{% for t in threats[:5] %}
{{ loop.index }}. **[{{ t.cvss_severity }}] {{ t.threat_title }}**
   - Target: {{ t.target_name }}
   - CVSS: {{ t.cvss_base_score }} | {{ t.cvss_vector }}
   - Risk: {{ t.risk_statement }}
{% endfor %}

---

## System Components

| ID | Name | Type | Trust Level | Technologies |
|----|------|------|-------------|--------------|
{% for c in components %}
| {{ c.id }} | {{ c.name }} | {{ c.type }} | {{ c.trust_level }} | {{ c.tech_stack | join(", ") }} |
{% endfor %}

---

## Threat Register

| Priority | ID | Framework | Category | Threat | Target | CVSS | Severity |
|----------|----|-----------|----------|--------|--------|------|----------|
{% for t in threats %}
| {{ t.priority }} | {{ t.threat_id }} | {{ t.threat_source }} | {{ t.threat_category }} | {{ t.threat_title }} | {{ t.target_name }} | {{ t.cvss_base_score }} | {{ t.cvss_severity }} |
{% endfor %}

---

## Threat Details

{% for t in threats %}
### {{ t.threat_id }}: {{ t.threat_title }}

**Priority:** #{{ t.priority }} | **Framework:** {{ t.threat_source }} | **Category:** {{ t.threat_category_name }}
**Target:** {{ t.target_name }} | **CVSS Score:** {{ t.cvss_base_score }} ({{ t.cvss_severity }})
**CVSS Vector:** `{{ t.cvss_vector }}`
**CWE:** {{ t.cwe_id }} — {{ t.cwe_name }}
**OWASP:** {{ t.owasp_category }}

**Description**
{{ t.threat_description }}

**Attack Scenario**
{{ t.attack_scenario }}

**Attacker Profile:** {{ t.attacker_profile }}
**Prerequisites:** {{ t.prerequisites }}
**Impact:** {{ t.impact }}
**Likelihood:** {{ t.likelihood }}

> **Risk Statement:** {{ t.risk_statement }}

**Mitigation ({{ t.mitigation_type }}):**
{{ t.mitigation }}

**Remediation Effort:** {{ t.remediation_effort }}
**Remediation Timeline:** {{ t.remediation_timeline }}

---
{% endfor %}

## Remediation Roadmap

### 🔴 Immediate Action — Critical Findings (within 24 hours)
{% set critical = threats | selectattr("cvss_severity", "equalto", "Critical") | list %}
{% if critical %}
{% for t in critical %}
- [ ] **{{ t.threat_id }}** {{ t.threat_title }} — {{ t.mitigation }}
{% endfor %}
{% else %}
No Critical findings.
{% endif %}

### 🟠 Short-term — High Findings (within 1 week)
{% set high = threats | selectattr("cvss_severity", "equalto", "High") | list %}
{% if high %}
{% for t in high %}
- [ ] **{{ t.threat_id }}** {{ t.threat_title }} — {{ t.mitigation }}
{% endfor %}
{% else %}
No High findings.
{% endif %}

### 🟡 Medium-term — Medium Findings (within 1 month)
{% set medium = threats | selectattr("cvss_severity", "equalto", "Medium") | list %}
{% if medium %}
{% for t in medium %}
- [ ] **{{ t.threat_id }}** {{ t.threat_title }} — {{ t.mitigation }}
{% endfor %}
{% else %}
No Medium findings.
{% endif %}

### 🟢 Long-term — Low Findings (this quarter)
{% set low = threats | selectattr("cvss_severity", "equalto", "Low") | list %}
{% if low %}
{% for t in low %}
- [ ] **{{ t.threat_id }}** {{ t.threat_title }} — {{ t.mitigation }}
{% endfor %}
{% else %}
No Low findings.
{% endif %}

---
*Report generated by ThreatLens AI. Validate all AI-generated findings with human security review.*
"""


# ── Report Generator ──────────────────────────────────────────────────────────
def generate_report(
    architecture: dict,
    scored_threats: list,
    severity_summary: dict,
    output_dir: str = "outputs"
) -> tuple:
    """
    Generate a Markdown threat model report.

    Returns:
        report_path (str): Path to saved report file
        report_content (str): Full report as string
    """
    Path(output_dir).mkdir(exist_ok=True)

    # Count threats by framework
    stride_count = len([
        t for t in scored_threats
        if t.get("threat_source") == "STRIDE"
    ])
    single_agent_count = len([
        t for t in scored_threats
        if t.get("threat_source") == "SINGLE-AGENT"
    ])
    multi_agent_count = len([
        t for t in scored_threats
        if t.get("threat_source") == "MULTI-AGENT"
    ])

    # Render template
    env = Environment(loader=FileSystemLoader("."))
    template = env.from_string(REPORT_TEMPLATE)

    report_content = template.render(
        system_name=architecture.get("system_name", "Unnamed System"),
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M UTC"),
        total_threats=len(scored_threats),
        component_count=len(architecture.get("components", [])),
        flow_count=len(architecture.get("data_flows", [])),
        severity_summary=severity_summary,
        stride_count=stride_count,
        single_agent_count=single_agent_count,
        multi_agent_count=multi_agent_count,
        components=architecture.get("components", []),
        data_flows=architecture.get("data_flows", []),
        threats=scored_threats
    )

    # Save to file
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    system_slug = (
        architecture.get("system_name", "report")
        .lower()
        .replace(" ", "_")
        .replace("/", "_")
    )
    filename = f"{output_dir}/{system_slug}_{timestamp}.md"

    with open(filename, "w") as f:
        f.write(report_content)

    return filename, report_content


# ── Test Runner ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("\n🧪 Testing reporter with sample data...\n")

    sample_arch = {
        "system_name": "Multi-Agent DevSecOps Pipeline",
        "components": [
            {
                "id": "comp_1",
                "name": "GitHub Repository",
                "type": "other",
                "tech_stack": ["GitHub"],
                "trust_level": "INTERNET",
                "description": "Source code repo"
            },
            {
                "id": "comp_2",
                "name": "LangGraph Orchestrator",
                "type": "AI",
                "tech_stack": ["LangGraph", "Python"],
                "trust_level": "INTERNAL",
                "description": "Multi-agent supervisor"
            },
            {
                "id": "comp_3",
                "name": "Scanner Agent",
                "type": "AI",
                "tech_stack": ["Claude", "Semgrep"],
                "trust_level": "INTERNAL",
                "description": "SAST scanning agent"
            }
        ],
        "data_flows": [
            {
                "id": "flow_1",
                "from": "comp_1",
                "to": "comp_2",
                "data_type": "PR webhook",
                "protocol": "HTTPS",
                "encrypted": True,
                "authenticated": True,
                "crosses_trust_boundary": True
            }
        ],
        "trust_boundaries": [],
        "tech_stack_summary": ["LangGraph", "Claude", "Semgrep"],
        "parser_notes": "Test architecture"
    }

    sample_threats = [
        {
            "threat_id": "T001",
            "target_id": "comp_2",
            "target_name": "LangGraph Orchestrator",
            "target_type": "component",
            "threat_source": "MULTI-AGENT",
            "threat_category": "MA09",
            "threat_category_name": "MA09: Compromised Orchestrator",
            "threat_title": "Orchestrator Hijacked via Prompt Injection",
            "threat_description": "Attacker hijacks orchestrator to redirect all agents",
            "attack_scenario": "Step 1: Inject malicious prompt. Step 2: Orchestrator compromised. Step 3: All agents redirected.",
            "attack_vector": "Inter-Agent",
            "attacker_profile": "External Attacker",
            "prerequisites": "Access to pipeline input",
            "impact": "Full pipeline compromise",
            "likelihood": "High",
            "cwe_id": "N/A",
            "cwe_name": "N/A",
            "owasp_category": "N/A",
            "mitigation": "Implement human-in-the-loop approval for all irreversible actions",
            "mitigation_type": "Preventive",
            "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:H/I:H/A:H",
            "cvss_base_score": 9.9,
            "cvss_severity": "Critical",
            "priority": 1,
            "risk_statement": "IF orchestrator is hijacked THEN all agents are compromised",
            "remediation_effort": "High",
            "remediation_timeline": "Immediate (24h)"
        },
        {
            "threat_id": "T002",
            "target_id": "comp_3",
            "target_name": "Scanner Agent",
            "target_type": "component",
            "threat_source": "SINGLE-AGENT",
            "threat_category": "SA01",
            "threat_category_name": "SA01: Prompt Injection",
            "threat_title": "Prompt Injection via Malicious Code Comment",
            "threat_description": "Malicious comments in PR code hijack Scanner Agent",
            "attack_scenario": "Step 1: Attacker adds malicious comment. Step 2: Agent reads code. Step 3: Agent follows injected instructions.",
            "attack_vector": "Prompt",
            "attacker_profile": "External Attacker",
            "prerequisites": "Ability to submit PR",
            "impact": "Agent performs unauthorized actions",
            "likelihood": "High",
            "cwe_id": "N/A",
            "cwe_name": "N/A",
            "owasp_category": "LLM01:2025",
            "mitigation": "Sanitize all code content before including in agent context",
            "mitigation_type": "Preventive",
            "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:L",
            "cvss_base_score": 8.3,
            "cvss_severity": "High",
            "priority": 2,
            "risk_statement": "IF malicious code comment is submitted THEN Scanner Agent is hijacked",
            "remediation_effort": "Medium",
            "remediation_timeline": "Short-term (1 week)"
        },
        {
            "threat_id": "T003",
            "target_id": "comp_1",
            "target_name": "GitHub Repository",
            "target_type": "component",
            "threat_source": "STRIDE",
            "threat_category": "T",
            "threat_category_name": "Tampering",
            "threat_title": "Webhook Payload Tampering",
            "threat_description": "Attacker tampers with GitHub webhook payload",
            "attack_scenario": "Step 1: Intercept webhook. Step 2: Modify payload. Step 3: Pipeline processes malicious data.",
            "attack_vector": "Network",
            "attacker_profile": "External Attacker",
            "prerequisites": "Network position to intercept traffic",
            "impact": "Pipeline processes attacker-controlled data",
            "likelihood": "Low",
            "cwe_id": "CWE-345",
            "cwe_name": "Insufficient Verification of Data Authenticity",
            "owasp_category": "A08:2021",
            "mitigation": "Verify GitHub webhook signatures using HMAC-SHA256",
            "mitigation_type": "Preventive",
            "cvss_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "cvss_base_score": 5.9,
            "cvss_severity": "Medium",
            "priority": 3,
            "risk_statement": "IF webhook is tampered THEN pipeline processes malicious data",
            "remediation_effort": "Low",
            "remediation_timeline": "Short-term (1 week)"
        }
    ]

    severity_summary = {
        "Critical": 1,
        "High": 1,
        "Medium": 1,
        "Low": 0,
        "Informational": 0,
        "Unknown": 0
    }

    report_path, report_content = generate_report(
        sample_arch,
        sample_threats,
        severity_summary
    )

    print(f"✅ Report generated successfully!")
    print(f"   Path: {report_path}")
    print(f"   Size: {len(report_content)} characters")
    print(f"   Lines: {len(report_content.splitlines())}")
    print(f"\n--- Report Preview (first 20 lines) ---\n")
    for line in report_content.splitlines()[:20]:
        print(f"   {line}")
    print(f"\n   ... ({len(report_content.splitlines())} total lines)")
    print(f"\n✅ Open outputs/ folder to see the full report!")